#!/usr/bin/env bash

# Pipe by Jerred Shepherd
# 0.1.2

source "${BASH_SOURCE%/*}/includes/util.sh"
source "${BASH_SOURCE%/*}/includes/commands/backup.sh"
source "${BASH_SOURCE%/*}/includes/commands/clean.sh"
source "${BASH_SOURCE%/*}/includes/commands/create.sh"
source "${BASH_SOURCE%/*}/includes/commands/destroy.sh"
source "${BASH_SOURCE%/*}/includes/commands/download.sh"
source "${BASH_SOURCE%/*}/includes/commands/restart.sh"
source "${BASH_SOURCE%/*}/includes/commands/send.sh"
source "${BASH_SOURCE%/*}/includes/commands/start.sh"
source "${BASH_SOURCE%/*}/includes/commands/stop.sh"
source "${BASH_SOURCE%/*}/includes/commands/update.sh"
source "${BASH_SOURCE%/*}/config"

declare -A bungeecord_versions

help() {
    printf "Created by Jerred Shepherd
Pipe 0.1.2 Usage:
pipe [command] [-arguments]
 where commands are

    Name              Function                                 Accepted Arguments
   ######            ##########                               ####################
    backup            Backup a server                          nas
    clean             Clean a servers log files                nac
    create            Create a new server                      nptvb
    destroy           Destroy a server                         nc
    download          Download the latest version of a jar     tv
    restart           Restart a server                         na
    send              Send a command to a server               nad
    start             Start a server                           naf
    stop              Stop a server                            nak
    update            Update a server                          nas

 General Arguments

      Name              Description
     ######            #############
      -n <name>         Server name
      -v <version>      Version 
                        For Spigot: Use Minecraft version number (eg 1.10.2) or 'latest'
                        For BungeeCord: Use BungeeCord build number (eg 1208) or 'latest'
                        For BuildTools: This doesn't apply
      -a                Apply the operation to all servers
      -c                Don't ask for confirmation; currently unused
      -s                Stop the server if it's running before doing the operation; currently unused

 Create Arguments
      -p <port>         Server port
      -t <type>         Server type (spigot or bungeecord)
      -b <name>         Base server; currently unused

 Start Arguments
      -f                Force startup; Kill any process using the servers port; currently unused

 Stop Arguments
      -k                Kill the server immediately; don't wait for it to stop; currently unused\n"
}

main() {
    getopt --test > /dev/null
    if [[ $? -ne 4 ]]; then
        echo "Sorry, `getopt --test` failed in this environment."
        exit 1
    fi

    command="$1"

    case "$command" in
        "backup")
            backup "$@"
            ;;
        "clean")
            clean "$@"
            ;;
        "create")
            create "$@"
            ;;
        "destroy")
            destroy "$@"
            ;;
        "download")
            download "$2" "$3"
            ;;
        "restart")
            restart "$2" "$3"
            ;;
        "send")
            send "$@"
            ;;
        "start")
            start "$@"
            ;;
        "stop")
            stop "$@"
            ;;
        "update")
            update "$2" "$3"
            ;;
        *)
            help
            ;;
    esac
}

main "$@"
